name: CI
on:
  push:
  release:
    types:
      - created

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - run: npm install
      - uses: docker://colinfang/vsce
        with:
          args: package
      - uses: actions/upload-artifact@v2-preview
        with:
          name: vsix
          path: "*.vsix"

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/download-artifact@v2-preview
        with:
          name: vsix
      - id: find_file_name
        run: echo "::set-output name=file::$(ls *.vsix)"
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.find_file_name.outputs.file }}
          asset_name: ${{ steps.find_file_name.outputs.file }}
          asset_content_type: application/zip
